services:
  - name: web
    type: web
    buildCommand: |
      cd client && npm install && npm run build
      cd .. && bundle install
    startCommand: bundle exec rails s -p $PORT
    healthCheckPath: "/"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        value: 7bb030ab5f678bbd658762142f83f62d
      - key: DATABASE_URL
        value: <%= ENV['DATABASE_URL'] %>
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
